/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manage_your_music_v1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author arets
 */
public class MusicManagementAppGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicManagementAppGUI
     */
    public MusicManagementAppGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRINT = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTA1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayTA2 = new javax.swing.JTextArea();
        removeBTN = new javax.swing.JButton();
        moveBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        printBTN = new javax.swing.JButton();
        removeBTN2 = new javax.swing.JButton();
        removeBTN1 = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        songTF = new javax.swing.JTextField();
        artistTF = new javax.swing.JTextField();
        genreTF = new javax.swing.JTextField();
        albumTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        displayTA3 = new javax.swing.JTextArea();
        searchTF = new javax.swing.JTextField();
        genreCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        displayTA1.setColumns(20);
        displayTA1.setRows(5);
        jScrollPane2.setViewportView(displayTA1);

        displayTA2.setColumns(20);
        displayTA2.setRows(5);
        jScrollPane3.setViewportView(displayTA2);

        removeBTN.setText("REMOVE");
        removeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTNActionPerformed(evt);
            }
        });

        moveBTN.setText("MOVE");
        moveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        printBTN.setText("PRINT");
        printBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBTNActionPerformed(evt);
            }
        });

        removeBTN2.setText("REMOVE");
        removeBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTN2ActionPerformed(evt);
            }
        });

        removeBTN1.setText("REMOVE");
        removeBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTN1ActionPerformed(evt);
            }
        });

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Album");

        jLabel2.setText("Artist");

        jLabel3.setText("Song");

        jLabel4.setText("PlayList1 ");

        jLabel5.setText("Genre");

        songTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songTFActionPerformed(evt);
            }
        });

        artistTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistTFActionPerformed(evt);
            }
        });

        genreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreTFActionPerformed(evt);
            }
        });

        albumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumTFActionPerformed(evt);
            }
        });

        searchBTN.setText("SEARCH");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("PlayList2");

        displayTA3.setColumns(20);
        displayTA3.setRows(5);
        jScrollPane4.setViewportView(displayTA3);

        genreCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Rock", "Hard Rock ", "Classic ", "Pank Rock", "Hip Hop" }));

        javax.swing.GroupLayout PRINTLayout = new javax.swing.GroupLayout(PRINT);
        PRINT.setLayout(PRINTLayout);
        PRINTLayout.setHorizontalGroup(
            PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRINTLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRINTLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(removeBTN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PRINTLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeBTN2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(424, 424, 424))
                    .addGroup(PRINTLayout.createSequentialGroup()
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PRINTLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(searchTF, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PRINTLayout.createSequentialGroup()
                                    .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(artistTF)
                                        .addComponent(albumTF)
                                        .addComponent(genreTF)
                                        .addComponent(songTF)
                                        .addComponent(addBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(genreCB, 0, 160, Short.MAX_VALUE))
                                    .addGap(45, 45, 45)
                                    .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRINTLayout.createSequentialGroup()
                                            .addComponent(removeBTN)
                                            .addGap(18, 18, 18)
                                            .addComponent(moveBTN)
                                            .addGap(18, 18, 18)
                                            .addComponent(deleteBTN)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(printBTN))))
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PRINTLayout.setVerticalGroup(
            PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRINTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRINTLayout.createSequentialGroup()
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(songTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(artistTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(albumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printBTN)
                        .addComponent(deleteBTN)
                        .addComponent(moveBTN)
                        .addComponent(removeBTN))
                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRINTLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(genreCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBTN)
                            .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRINTLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBTN1)
                    .addComponent(removeBTN2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PRINTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRINTLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(exitBTN)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PRINT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PRINT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void songTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songTFActionPerformed

    private void artistTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistTFActionPerformed

    private void albumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumTFActionPerformed

    private void genreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreTFActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        // Retrieve song information from text fields
    String song = songTF.getText();
    String artist = artistTF.getText();
    String album = albumTF.getText();
    String genre = genreTF.getText();
    
    // Create a string representing the song information
    String songInfo = "Song: " + song + "\nArtist: " + artist + "\nAlbum: " + album + "\nGenre: " + genre + "\n";
    
    // Append the song information to the display text area
    displayTA.append(songInfo);
    
    // Clear the text fields for the next input
    songTF.setText("");
    artistTF.setText("");
    albumTF.setText("");
    genreTF.setText("");

    
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void removeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTNActionPerformed
        // TODO add your handling code here:
        
        int caretPosition = displayTA.getCaretPosition();
    try {
        int lineStartOffset = displayTA.getLineStartOffset(displayTA.getLineOfOffset(caretPosition));
        int lineEndOffset = displayTA.getLineEndOffset(displayTA.getLineOfOffset(caretPosition));
        displayTA.replaceRange("", lineStartOffset, lineEndOffset);
    } catch (BadLocationException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_removeBTNActionPerformed

    private void moveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBTNActionPerformed
        // TODO add your handling code here:
        
         int selectedIndex = displayTA.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedSong = displayTA.getSelectedValue();
            displayTA.replaceRange("", displayTA.getLineStartOffset(selectedIndex), displayTA.getLineEndOffset(selectedIndex));
            displayTA1.append(selectedSong + "\n");
        }
    }//GEN-LAST:event_moveBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        
         int selectedIndex = displayTA.getSelectedIndex();
        if (selectedIndex != -1) {
            displayTA.replaceRange("", displayTA.getLineStartOffset(selectedIndex), displayTA.getLineEndOffset(selectedIndex));
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void printBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBTNActionPerformed
        // TODO add your handling code here:
        
       JOptionPane.showMessageDialog(this, displayTA.getText(), "Playlist", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_printBTNActionPerformed

    private void removeBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTN1ActionPerformed
        // TODO add your handling code here:
          // Remove the selected song from the second playlist
        int selectedIndex = displayTA1.getSelectedIndex();
        if (selectedIndex != -1) {
            displayTA1.replaceRange("", displayTA1.getLineStartOffset(selectedIndex), displayTA1.getLineEndOffset(selectedIndex));
        }
        
    }//GEN-LAST:event_removeBTN1ActionPerformed

    private void removeBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTN2ActionPerformed
        // TODO add your handling code here:
         // Remove the selected song from the third playlist
        int selectedIndex = displayTA2.getSelectedIndex();
        if (selectedIndex != -1) {
            displayTA2.replaceRange("", displayTA2.getLineStartOffset(selectedIndex), displayTA2.getLineEndOffset(selectedIndex));
        }
    }//GEN-LAST:event_removeBTN2ActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
          // Get the search query from the text field
    String searchQuery = searchTF.getText().trim().toLowerCase();
            // Clear the search results display
    displayTA3.setText("");
    
    
     // Iterate through the songs in the playlist to find matches
    DefaultListModel<String> model = (DefaultListModel<String>) displayTA.getModel();
    for (int i = 0; i < model.size(); i++) {
        String song = model.getElementAt(i);
        if (song.toLowerCase().contains(searchQuery)) {
            // If the song matches the search query, add it to the search results display
            displayTA3.append(song + "\n");
        }
    }
    
    
    
    }//GEN-LAST:event_searchBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicManagementAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicManagementAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicManagementAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicManagementAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicManagementAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PRINT;
    private javax.swing.JButton addBTN;
    private javax.swing.JTextField albumTF;
    private javax.swing.JTextField artistTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JTextArea displayTA1;
    private javax.swing.JTextArea displayTA2;
    private javax.swing.JTextArea displayTA3;
    private javax.swing.JButton exitBTN;
    private javax.swing.JComboBox<String> genreCB;
    private javax.swing.JTextField genreTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton moveBTN;
    private javax.swing.JButton printBTN;
    private javax.swing.JButton removeBTN;
    private javax.swing.JButton removeBTN1;
    private javax.swing.JButton removeBTN2;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField searchTF;
    private javax.swing.JTextField songTF;
    // End of variables declaration//GEN-END:variables
}
